// <auto-generated />
namespace ShopDunk.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class SaveImagesToDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SaveImagesToDB));
        
        string IMigrationMetadata.Id
        {
            get { return "202511181703597_SaveImagesToDB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
